server:
  port: 8082

spring:
  application:
    name: gateway-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://darecaga.cafe24.com:3306/darecaga?characterEncoding=UTF-8&serverTimezone=UTC
    username: darecaga
    password: aresteam!
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id  : match-api
          uri : lb://match-api
          predicates:
            - Path=/api/matches, /api/matches/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

